
const ruta_local_orquestador = process.env.RUTA_LOCAL_ORQUESTADOR ?? '172.17.0.1';
const updateCursobyPhone = async (phone: string, curso: string): Promise<boolean> => {
    const respuesta = await fetch(`http://${ruta_local_orquestador}:8000/api/leads`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          phone,
          curso
        }),
    });
    if (!respuesta.ok) {
        console.error("Error en la solicitud:", respuesta.status, await respuesta.text());
        return false;
    }else {
        return true;
    }
}
export const selectedCurso = async (phone: string ,option: number, promocion: number): Promise<{ flag: boolean, curso: string }> => {
    const curso = selectCurso(option,promocion);
    const flag = await updateCursobyPhone(phone, curso);
    return {flag,curso};
} 
export const consultayselectedCurso = async (phone: string, option: number):Promise<{ flag: boolean, curso: string }> => {
    const respuesta = await fetch(`http://${ruta_local_orquestador}:8000/api/leads?number=${phone}`, {
        method: "GET",
        headers: { "Content-Type": "application/json" }
      });
    if (!respuesta.ok) {
        console.error("Error en la solicitud:", respuesta.status, await respuesta.text());
    }else {
        const data = await respuesta.json();
        const curso = selectCurso(option, data.lead.flowId)

        const flag = await updateCursobyPhone(phone, curso);
        return {flag,curso};
    }
    
}
const CursosPromoVerano = [
    "VALORIZACION Y LIQUIDACION DE OBRAS PUBLICAS Y PRIVADAS",
    "METRADOS, COSTOS Y PRESUPUESTO EN EDIFICACIONES CON S10",
    "MAESTRO DE OBRA EN EDIFICACIONES",
    "RESIDENCIA Y SUPERVISION DE OBRAS PUBLICAS Y PRIVADAS",
    "ASISTENTE TECNICO DEL RESIDENTE Y SUPERVISOR DE OBRAS PUBLICAS Y PRIVADAS",
    "ESTABILIDAD DE TALUDES",
    "MECANICA DE SUELOS Y PAVIMENTOS",
    "GESTION DE LA CONSTRUCCION CON PRIMAVERA P6 Y POWER BI",
    "PLANIFICACION, PROGRAMACION Y CONTROL DE OBRAS CON MS PROJECT Y LAST PLANNER SYSTEM",
    "GESTION DEL RIESGO DE DESASTRES",
    "SUPERVISOR SSOMA",
    "SEGURIDADM, SALUD OCUPACIONAL Y MEDIO AMBIENTE - SSOMA",
    "TOPOGRAFIA CON DRONES",
    "TOPOGRAFIA Y DISEÑO DE CARRETERAS CON AUTODESK CIVIL 3D",
    "AUTODESK CIVIL 3D APLICADO A LA TOPOGRAFIA Y DISEÑO DE CARRETERAS",
    "MANTENIMIENTO DE INFRAESTRUCTURA VIAL EN CAMINOS VECINALLES Y DEPARTAMENTALES",
    "MANTENIMIENTO RUTINARIO Y PERIODICO EN CAMINOS VECINALES Y DEPARTAMENTALES",
    "MANTENIMIENTO DE CARRETERAS VECINALES Y DEPARTAMENTALES",
    "DEFENSA CIVIL EN INSPECCIONES TECNICAS DE SEGURIDAD EN EDIFICACIONES",
    "DISEÑO DE CIMENTACIONES, PILOTES Y MUROS DE CONTENCION",
    "CONSTRUCCION Y DISEÑO DE ESTRUCTURAS SISMORRESISTENTES",
    "CONTRATOS NEC Y FIDIC",
    "ESTRUCTURAS E INGENIERIA SISMICA EN PROYECTOS DE CONSTRUCCION",
    "ESTUDIO DEL IMPACTO AMBIENTAL CON ARCGIS",
    "GEOMECANICA MINERA",
    "PROGRMA INTERNACIONAL EN GERENCIA DE LA CONSTRUCCION",
    "DISEÑO DE ESTRUCTURAS DE ALBAÑILERIA",
    "DISEÑO PARA CONSTRUCCION EN ACERO",
    "GESTION DE PERFORACION Y VOLADURA EN MINERIA SUPERFICIAL Y SUBTERRANEA",
    "MECANICA DE SUELOS EN CIMENTACIONES",
    "DISEÑO DE PAVIMENTOS NUEVOS Y REHABILITACION",
    "REGLAMENTO DE SEGURIDAD Y SALUD EN EL TRABAJO EN OBRAS DE CONSTRUCCION D.S 001-2019-TR NORMA TECNICA G 050",
    "DISEÑO DE OBRAS DE DRENAJE EN CARRETERA",
    "LECTURA, INTERPRETACION Y REPRESENTACION DE PLANOS EN PROYECTOS DE CONTRUCCION CIVIL",
    "COORDINADOR BIM",
    "BIM REVIT ARQUITECTURA",
    "BIM REVIT ESTRUCTURAS",
    "ANALISIS DE DATOS CON POWER BI",
    "OFFICE PROFESIONAL - WORD Y EXCEL INTERMEDIO",
    "BUSSINES INTELLIGENCE CON SQL SERVER",
    "DISEÑO DE PUENTES DE CONCRETO ARMADO Y PRESFORZADO",
    "ELABORACION DE EXPEDIENTES TECNICO DE OBRA",
    "SSOMA APLICACO AL SECTOR CONSTRUCCION, INDUSTRIAL MINERO Y MINERO",
    "EXCEL INGENIERO",
    "TOPOGRAFIA CON DRONES Y PREPARACION PARA LICENCIAMIENTO DE VUELO",
    "GERENCIA EN PROYECTOS DE CONSTRUCCION",
    "DISEÑO DE REDES DE AGUA Y SANEAMIENTO",
    "TRIBUTACION EMPRESARIAL",
    "METODOLOGIAS AGILES ESPECIALISTA EN INNOVACION Y EJECUCION EFICAZ DE PROYECTOS Y STARTUPS",
    "CONTROL DE OPERACIONES MINERAS",
    "VENTILACION MINERA",
    "GESTION AMBIENTAL MINERA",
    "PERFORACION Y VOLADURA EN MINERIA SUBTERRANEA",
    "PERFORACION Y VOLADURA EN MINERIA Y CARRETERAS"
]
const CursosArmatuPack = [
    "CONTRATACIONES DEL ESTADO",
    "LEY DE CONTRATACIONES DEL ESTADO DURANTE LA EJECUCION DE OBRAS PUBLICAS",
    "PREPARACION PARA LA CERTIFICACION OSCE",
    "ADMINISTRACION Y GESTION PUBLICA",
    "FESTION MUNICIPAL",
    "GESTION PUBLICA",
    "PEI Y POI - APLICATIVO CEPLAN",
    "PLANES DE DESARROLLO CONCERTADO REGIONAL Y LOCAL",
    "PRESUPUESTO PUBLICO POR RESULTADOS",
    "ASISTENTE ADMINISTRATIVO EN LA GESTION PUBLICA",
    "SISTEMAS ADMINISTRATIVOS DEL ESTADO: SIGA, SEACE, SIAF",
    "CIERRE CONTABLE EN EL SIAF - PLATAFORMA WEB",
    "SIGA - MODULO LOGISTICO Y GESTION DE ALMACENES",
    "PERFILES, FICHAS TEC Y EXPEDIENTES TECNICOS EN EL MARCO DEL INVIERTE.PE",
    "PLANEAMIENTO ESTRATEGICO EN EL SECTOR SALUD",
    "FICHAS TECNICAS E INVERSIONES DE OPTIMIZACION, AMPLIACION MARGINAL, REPOSICION Y REHABILITACION-IOARR",
    "PROGRAMACION, FORMULACION Y EVALUACION DE PROYECTOS DE INVERSION INVIERTE.PE",
    "INVERTE.PE",
    "FORMULACION Y GESTION DDE PROYECTOS DE I+D+I PARA FONDOS CONCURSALES",
    "GESTION DE RECURSOS HUMANOS Y LEY SERVIR",
    "ENFOQUE DE GENERO",
    "COACHING Y LIDERAZGO",
    "AUDITORIA Y CONTROL GUBERNAMENTAL",
    "ADMINISTRACION DOCUMENTARIA Y DE ARCHIVO EN EL SECTOR PUBLICO",
    "TRAMITE DOCUMENTARIO Y GESTION DE ARCHIVOS EN EL SECTOR PUBLICO",
    "ANALIS DE DATOS CON PROWER BI",
    "OFFICE PROFESIONAL - WORD Y EXCEL INTERMEDIO",
    "BUSINESS ONTELLIGENCE CON SQL SERVER",
    "DERECHO PENAL Y DELITOS CONTRA LA ADMINISTRACION PUBLICA",
    "DERECHO ADMINISTRATIVO",
    "DERECHO PENAL, NUEVO CODIGO PROCESAL PENAL, PRISION PREVENTIVA, DELITOS CONTRA LA ADMINISTRACION PUBLICA Y ANTICORRUPCION",
    "VALORIZACION Y LIQUIDACION DE OBRAS PUBLICAS Y PRIVADAS",
    "METRADOS, COSTOS Y PRESUPUESTO EN EDIFICACIONES CON S10",
    "MAESTRO DE OBRA EN EDIFICACIONES",
    "RESIDENCIA Y SUPERVISION DE OBRAS PUBLICAS Y PRIVADAS",
    "ASISTENTE TECNICO DEL RESIDENTE Y SUPERVISOR DE OBRAS PUBLICAS Y PRIVADAS",
    "ESTABILIDAD DE TALUDES",
    "MECANICA DE SUELOS Y PAVIMENTOS",
    "MENTENIMIENTO RUTINARIO Y PERIODICO EN CAMINOS VECINALES Y DEPARTAMENTALES",
    "DISEÑO DE PAVIMENTOS NUEVOS Y REHABILITACION",
    "GESTION DE LA CONTRUCCION CON PRIMAVERA P6 Y POWER BI",
    "PLANIFICACION, PROGRAMACION Y CONTROL DE OBRAS CON MS PROJECT Y LAST PLANNER SYSTEM",
    "GESTION DEL RIESGO DE DESASTRES",
    "SUPERVISOR SSOMA",
    "SEGURIDAD, SALUD OCUPACIONAL Y MEDIO AMBIENTE - SSOMA",
    "REGLAMENTO DE SEGURIDAD Y SALUD EN EL TRABAJO EN OBRAS DE CONSTRCCIUON D.S 011-2019- TR NORMA TECNICA G050",
    "DISEÑO DE OBRAS DE DRENAJE EN CARRETERA",
    "AUTODESK CIVIL 3D APLICADO A LA TOPOGRAFIA Y DISEÑO DE CARRETERAS",
    "TOPOGRAFICA CON DRONES",
    "TOPOGRAFIA Y DISEÑO DE CARRETERAS CON AUTODESK CIVIL 3D",
    "LECTURA, INTERPRETACION Y REPRESENTACION DE PLANOS EN PROYECTOS DE CONSTRUCCION CIVIL",
    "COORDINADOR BIM",
    "BIM REVIT ARQUITECTURA",
    "BIM REVIT ESTRUCTURAS",
    "CONTROL DE OPERACIONES MINERAS",
    "GESTION AMBIENTAL MINERA",
    "VENTILACION MINERA",
    "PERFORACION Y VOLADURA EN MINERIA SUBTERRANEA",
    "PERFORACION Y VOLADURA EN MINERIA Y CARRETERAS",
    "DISEÑO DE PUENTES DE CONCRETO ARMADO Y PRESFORZADO",
    "CONSTRUCCION Y DISEÑO DE ESTRUCTURAS SISMORRESISTENTES",
    "ELABORACION DE EXPEDIENTES TECNICO DE OBRA"
]
const selectCurso = (option:number, promo:number):string => {
    if(promo == 1){
        return CursosPromoVerano[option-1];
    }else if(promo == 2){
        return CursosArmatuPack[option-1];
    }else{
        return "NO SE ENCONTRO EN LISTA ESTATICA";
    }
}